version: "3.0"

services:

  daytrader-account-db:
    image: ibmcom/db2
    container_name: daytrader-account-db
    privileged: true
    networks:
      - daytrader
    environment:
      - DBNAME=tradedb
      - DB2INST1_PASSWORD=db2inst1
      - LICENSE=accept
    volumes:
      - daytrader-db2data-accounts:/database

  daytrader-holding-db:
    image: ibmcom/db2
    container_name: daytrader-holding-db
    privileged: true
    networks:
      - daytrader
    environment:
      - DBNAME=tradedb
      - DB2INST1_PASSWORD=db2inst1
      - LICENSE=accept
    volumes:
      - daytrader-db2data-holdings:/database

  daytrader-order-db:
    image: ibmcom/db2
    container_name: daytrader-order-db
    privileged: true
    networks:
      - daytrader
    environment:
      - DBNAME=tradedb
      - DB2INST1_PASSWORD=db2inst1
      - LICENSE=accept
    volumes:
      - daytrader-db2data-orders:/database

  daytrader-quote-db:
    image: ibmcom/db2
    container_name: daytrader-quote-db
    privileged: true
    networks:
      - daytrader
    environment:
      - DBNAME=tradedb
      - DB2INST1_PASSWORD=db2inst1
      - LICENSE=accept
    volumes:
      - daytrader-db2data-quotes:/database

  daytrader-frontend-service:
    build: ./daytrader-frontend-service
    image: daytrader-frontend-service
    container_name: daytrader-frontend-service
    networks:
      - daytrader
    ports:
      - "9080:9080"
    environment:
      - JVM_ARGS=-DaccountClient/mp-rest/url=http://daytrader-account-service:9080/accounts -DholdingClient/mp-rest/url=http://daytrader-holding-service:9080/holdings -DorderClient/mp-rest/url=http://daytrader-order-service:9080/orders -DquoteClient/mp-rest/url=http://daytrader-quote-service:9080/quotes
      - MAX_QUOTES=100
      - MAX_USERS=100

  daytrader-account-service:
    build: 
      context: ./daytrader-account-service
      dockerfile: Dockerfile-db2
    image: daytrader-account-service
    container_name: daytrader-account-service
    networks:
      - daytrader
    environment:
      - DB_HOST=daytrader-account-db
      - DB_PORT=50000
      - DB_NAME=TRADEDB
      - DB_USER=db2inst1
      - DB_PASSWORD=db2inst1
    volumes_from:
      - daytrader-account-db

  daytrader-holding-service:
    build: 
      context: ./daytrader-holding-service
      dockerfile: Dockerfile-db2
    image: daytrader-holding-service
    container_name: daytrader-holding-service
    networks:
      - daytrader
    environment:
      - DB_HOST=daytrader-holding-db
      - DB_PORT=50000
      - DB_NAME=TRADEDB
      - DB_USER=db2inst1
      - DB_PASSWORD=db2inst1
    volumes_from:
      - daytrader-holding-db

  daytrader-order-service:
    build: 
      context: ./daytrader-order-service
      dockerfile: Dockerfile-db2
    image: daytrader-order-service
    container_name: daytrader-order-service
    networks:
      - daytrader
    environment:
      - JVM_ARGS=-DaccountClient/mp-rest/url=http://daytrader-account-service:9080/accounts -DholdingClient/mp-rest/url=http://daytrader-holding-service:9080/holdings -DorderClient/mp-rest/url=http://daytrader-order-service:9080/orders -DquoteClient/mp-rest/url=http://daytrader-quote-service:9080/quotes
      - DB_HOST=daytrader-order-db
      - DB_PORT=50000
      - DB_NAME=TRADEDB
      - DB_USER=db2inst1
      - DB_PASSWORD=db2inst1
    volumes_from:
      - daytrader-order-db

  daytrader-quote-service:
    build: 
      context: ./daytrader-quote-service
      dockerfile: Dockerfile-db2
    image: daytrader-quote-service
    container_name: daytrader-quote-service
    networks:
      - daytrader
    environment:
      - DB_HOST=daytrader-quote-db
      - DB_PORT=50000
      - DB_NAME=TRADEDB
      - DB_USER=db2inst1
      - DB_PASSWORD=db2inst1
    volumes_from:
      - daytrader-quote-db

networks:
  daytrader:
    external: true

volumes:
  daytrader-db2data-accounts:
  daytrader-db2data-holdings:
  daytrader-db2data-orders:
  daytrader-db2data-quotes:
  
 
