FROM open-liberty:full

# Add build files
COPY --chown=1001:0 target/*.war /config/apps/
COPY --chown=1001:0 src/main/liberty/config/server.db2.xml /config/server.xml
COPY --chown=1001:0 /db2jars /opt/ol/wlp/usr/shared/resources/db2jars
